apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: access-key
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-key
            namespace: external-secrets
          sessionTokenSecretRef:
            name: aws-creds
            key: session-token
            namespace: external-secrets
