apiVersion: v1
kind: Service
metadata:
  name: ngo-service
  namespace: ngo-service
spec:
  selector:
    app: ngo-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
